# PASTE TARGET: SA#325  "Create Record for Next Operation"
# Model: stock.picking   Type: ir.actions.server (Execute Code), bound button
# Author: Mark Angelo S. Templanza / Elyon    Date: 2026-08-16
# Backup of the current prod code: ai_context/sa325_BACKUP.txt
#
# WHY THIS CHANGE (root cause, evidenced on vifel_08_16_2026)
# ----------------------------------------------------------
# Symptom: stock.quant 559629 sits at M/BF/A/CH2 holding -4,648.320 kg of
# HOLIDAY BEEF SIOMAI 960G (product 35338, owner CDO FOODSPHERE INC. (FG)),
# stamped 2026-08-14 11:10:29 UTC / 19:10:29 Manila. It is the ONLY negative
# quant in any blast-freeze chamber in the whole database.
#
# Cause: M/RR/05792 (picking 16633), a REGULAR (non-BF) receiving report, was
# generated by this action from M/BF/WR/00195 (picking 16632, Blast Freeze -
# OUT) via the "outgoing + is_blast_freeze_operation" branch. Its 16 move
# lines source from M/BF/A/CH2 and total exactly 4,648.320 kg, matching the
# negative to the gram. It is the only non-BF document in the database that
# sources from a BF chamber.
#
# Mechanism: record.copy() copies the moves. In Odoo 17 stock.move.location_id
# is a plain stored Many2one, NOT computed (odoo/addons/stock/models/
# stock_move.py:71), so the copy carries the BF chamber over verbatim and
# nothing recomputes it. Step 2 then wrote ONLY picking_type_id onto those
# moves, leaving location_id = M/BF/A/CH2 on a receiving report whose header
# said Partners/Vendors -> M/A. Move lines created under that move (12 at
# 2026-08-13 20:21:12, 4 more by hand at 20:33-20:34) inherited the chamber.
# The header was later corrected, the already-written lines were not, and
# validation deducted 4,648.320 kg from a chamber that held no matching lots.
#
# Note the branch table in Step 3: the ONLY transition that preserves the
# copied moves is "outgoing + BF" (BFWR -> regular RR), which is exactly the
# one transition that crosses out of blast-freeze into a non-BF document.
# BFRR -> BFWR and RR -> WR both unlink the moves, which is why this has
# never bitten anywhere else.
#
# WHAT CHANGED (2 fixes + 1 guard, everything else is byte-identical)
# ------------------------------------------------------------------
#   FIX 1  Header destination for the INCOMING next-operation is taken from
#          the picking type defaults instead of the hardcoded 5
#          (Partners/Customers), which is backwards for a receiving report.
#          Outgoing paths keep the original 4/5, so BFRR -> BFWR and
#          RR -> WR behave exactly as they do today. Blast radius is limited
#          to the BFWR -> RR step.
#   FIX 2  Step 2 now rewrites location_id / location_dest_id on the copied
#          moves, not just picking_type_id. This is the actual root-cause fix.
#   GUARD  "if not next_operation: raise UserError(...)" replaces a bare
#          AttributeError crash when a transfer matches none of the three
#          branches. Delete those two lines if you prefer it silent.
#
# DOES NOT FIX THE EXISTING DATA
# ------------------------------
# Quant 559629 still holds -4,648.320 kg at M/BF/A/CH2. It needs a separate
# correcting entry re-sourced from the correct chamber lots. This patch only
# stops new occurrences.
#
# ALSO WORTH DOING (not in this paste)
# ------------------------------------
# Validation guard: a picking whose picking_type_id.is_blast_freeze_operation
# is False must not carry any move or move line whose source location has
# x_studio_is_a_blast_freezer = True. That blocks the harm regardless of how
# the lines got there.
# Separately: "HOLIDAY BEEF SIOMAI 960G" exists as 3 duplicate product records
# (29927, 35338, 35339), which makes this class of mismatch easier to hit.
#
# ==========================================================================
# PASTE EVERYTHING BELOW THIS LINE INTO SA#325
# ==========================================================================

# Available variables:
#  - env: environment on which the action is triggered
#  - model: model of the record on which the action is triggered; is a void recordset
#  - record: record on which the action is triggered; may be void
#  - records: recordset of all records on which the action is triggered in multi-mode; may be void
#  - time, datetime, dateutil, timezone: useful Python libraries
#  - float_compare: utility function to compare floats based on specific precision
#  - log: log(message, level='info'): logging function to record debug information in ir.logging table
#  - _logger: _logger.info(message): logger to emit messages in server logs
#  - UserError: exception class for raising user-facing warning messages
#  - Command: x2many commands namespace
# To return an action, assign: action = {...}

current_operation = record.picking_type_id
next_operation = None
warehouse_id = record.picking_type_id.warehouse_id.id
to_source_location = 4
to_destination_location = 5

if current_operation.code == "incoming" and current_operation.is_blast_freeze_operation:
    picking_type = env['stock.picking.type'].search([('code', '=', "outgoing"), ('is_blast_freeze_operation', '=', True), ('warehouse_id', '=', warehouse_id)], limit=1)
    next_operation = picking_type
    # dest_to_source = record.location_dest_id.id



elif current_operation.code == "outgoing" and current_operation.is_blast_freeze_operation:
    picking_type = env['stock.picking.type'].search([('code', '=', "incoming"), ('is_blast_freeze_operation', '=', False), ('warehouse_id', '=', warehouse_id)], limit=1)
    next_operation = picking_type


elif current_operation.code == "incoming" and not current_operation.is_blast_freeze_operation:
    picking_type = env['stock.picking.type'].search([('code', '=', "outgoing"), ('is_blast_freeze_operation', '=', False), ('warehouse_id', '=', warehouse_id)], limit=1)
    next_operation = picking_type

# GUARD: previously this crashed with a bare AttributeError on next_operation.id
if not next_operation:
    raise UserError("No next operation type is configured for this transfer.")

# FIX 1: the BFWR -> RR step produces an INCOMING document, so a hardcoded
# destination of 5 (Partners/Customers) was backwards for a receiving report.
# Outgoing paths keep the original 4/5 so their behaviour is unchanged.
if next_operation.code == "incoming":
    to_source_location = next_operation.default_location_src_id.id or 4
    to_destination_location = next_operation.default_location_dest_id.id or record.location_dest_id.id


if current_operation.code == "outgoing" and current_operation.is_blast_freeze_operation:
    # Step 1: Copy the record with initial fields
    toNavigateto = record.copy({
        'picking_type_id': next_operation.id,
        'x_studio_last_operation_source_document': record.id,
        'location_dest_id': to_destination_location,
        'location_id': to_source_location,
        'state': 'draft',
        'x_studio_loading_dock_no': 'N/A',
        'truck_type': record.truck_type,
        'x_studio_trucks_plate_': record.x_studio_trucks_plate_,
        'x_studio_driver': record.x_studio_driver,
        'x_studio_start_time': record.x_studio_end_time,
        'x_studio_truck_time': record.x_studio_end_time,
        'x_studio_validated_by': False,
        'x_studio_checked_by': False,
        'x_studio_approved_by': False,
        'x_studio_gate_pass': record.x_studio_gate_pass,
        'x_studio_client_reference': record.x_studio_client_reference



    })
else:
    # Step 1: Copy the record with initial fields
    toNavigateto = record.copy({
        'picking_type_id': next_operation.id,
        'x_studio_last_operation_source_document': record.id,
        'location_dest_id': to_destination_location,
        'location_id': to_source_location,
        'state': 'draft',
        'x_studio_checked_by': False,
        'x_studio_client_reference': record.x_studio_client_reference,
        'truck_type': record.truck_type,
        'x_studio_trucks_plate_': record.x_studio_trucks_plate_,
        'x_studio_driver': record.x_studio_driver,
        'x_studio_start_time': record.x_studio_end_time,
        'x_studio_truck_time': record.x_studio_end_time,
        'x_studio_validated_by': False,
        'x_studio_approved_by': False,
        'x_studio_gate_pass': record.x_studio_gate_pass,

    })

# Step 2: Update the picking_type_id for move_ids_without_package
# FIX 2 (ROOT CAUSE): stock.move.location_id is a plain stored field in
# Odoo 17, so record.copy() carried the BF chamber (M/BF/A/CH2) over from the
# source BFWR. Writing only picking_type_id left the moves, and every move
# line later created under them, sourcing from the chamber on a non-BF
# receiving report. Rewrite the locations to match the new document.
toNavigateto.move_ids_without_package.write({
    'picking_type_id': next_operation.id,
    'location_id': to_source_location,
    'location_dest_id': to_destination_location,
})


# Step 3: Set all stock moves related to move_ids_without_package to draft



if current_operation.code == "outgoing" and current_operation.is_blast_freeze_operation:
    for move in toNavigateto.move_ids_without_package:
        # Step 3.1: Clear associated stock.move.line records
        # Step 3.2: Set the stock move state to 'draft'
        move.write({'state': 'draft'})
        move.move_line_ids.unlink()  # This will delete all move lines related to the move
        for current_move in record.move_ids_without_package:
            if move.product_id.id == current_move.product_id.id:
                move.write({'x_studio_packaging_unit': current_move.x_studio_packaging_unit, 'x_studio_min_unit': current_move.x_studio_min_unit})
else:
    toNavigateto.move_ids_without_package.unlink()

# Step 4: Define the action to navigate to the new record
action = {
    'type': 'ir.actions.act_window',
    'name': 'New Record',
    'res_model': record._name,
    'view_mode': 'form',
    'res_id': toNavigateto.id,
    'target': 'current',
}
